### ISSUE TITLE
SHA256 mismatch when importing Ruby 2.3 docs

### ISSUE THREAD

**Issue by andyw8** [rubyapi/rubyapi#1411]
When running `bin/rails import:ruby:all`, everything seemed to import successfully, but when it got Ruby 2.3:

```
✔ Importing Ruby 2.3 documentation
rails aborted!
SHA256 mismatch. Expected , but calculated: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_downloader.rb:101:in `verify_file_integerity'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_downloader.rb:51:in `fetch_ruby_archive'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_downloader.rb:27:in `download'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_downloader.rb:12:in `download'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_documentation_importer.rb:47:in `fetch_ruby_src_for_release'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_documentation_importer.rb:25:in `import'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/ruby_documentation_importer.rb:11:in `import'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/tasks/import.rake:30:in `block (4 levels) in <main>'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/tasks/import.rake:30:in `each'
/Users/andyw8/src/github.com/rubyapi/rubyapi/lib/tasks/import.rake:30:in `block (3 levels) in <main>'
Tasks: TOP => import:ruby:all
(See full trace by running task with --trace)
```

**Comment by andyw8** [comment]
Running `bin/rails import:ruby[2.1]` afterwards succeeded though.

**Comment by colby-swandale** [comment]
pushed a commit that should fix this issue https://github.com/rubyapi/rubyapi/commit/4f3e5d9a180c668cfa295f2184cc9cfd35484292 

Thank you for submitting the bug report 🙇🏻
