### ISSUE TITLE
Can't import documentation for all currently supported versions of ruby

### ISSUE THREAD

**Issue by bronzdoc** [rubyapi/rubyapi#301]
When I execute `./bin/rake import:ruby:all` I'm getting the following error:

```shell
./bin/rake import:ruby:all

W, [2020-02-22T21:44:22.385204 #91312]  WARN -- Skylight: [SKYLIGHT] [4.2.1] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
tar: Error opening archive: Unrecognized archive format
| Importing Ruby 2.7.0.pre.rc2 documentationrake aborted!
TypeError: no implicit conversion of nil into String
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:91:in `initialize'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:91:in `new'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:91:in `method_path'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:45:in `block (2 levels) in generate_objects'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:37:in `each'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:37:in `block in generate_objects'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:33:in `each'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:33:in `generate_objects'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/rubyapi_rdoc_generator.rb:25:in `generate'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/ruby_documentation_importer.rb:33:in `import'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/ruby_documentation_importer.rb:9:in `import'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/tasks/import.rake:26:in `block (4 levels) in <main>'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/tasks/import.rake:24:in `each'
/Users/bronzdoc/projects/rubyapi/rubyapi/lib/tasks/import.rake:24:in `block (3 levels) in <main>'
Tasks: TOP => import:ruby:all
```

The problem is happening in: https://github.com/rubyapi/rubyapi/blob/c81def6947891296e9cb1e9aa88b56162532d573/lib/ruby_documentation_importer.rb#L33

Opening this issue to track this problem, will investigate further.

**Comment by AlexWayfer** [comment]
I've faced with a similar error:

```
> ./bin/rake import:ruby[2.7]
W, [2020-04-03T02:01:31.161919 #254695]  WARN -- Skylight: [SKYLIGHT] [4.2.3] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
/home/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/alex/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/ Importing Ruby 2.7 documentationrake aborted!
TypeError: no implicit conversion of nil into String
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:93:in `initialize'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:93:in `new'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:93:in `method_path'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:47:in `block (2 levels) in generate_objects'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:39:in `each'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:39:in `block in generate_objects'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:35:in `each'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:35:in `generate_objects'
/home/alex/Projects/rubyapi/lib/rubyapi_rdoc_generator.rb:27:in `generate'
/home/alex/Projects/rubyapi/lib/ruby_documentation_importer.rb:35:in `import'
/home/alex/Projects/rubyapi/lib/ruby_documentation_importer.rb:11:in `import'
/home/alex/Projects/rubyapi/lib/tasks/import.rake:12:in `block (2 levels) in <main>'
Tasks: TOP => import:ruby
(See full trace by running task with --trace)
```

**Comment by bronzdoc** [comment]
Thanks @colby-swandale!
